# Generated by Django 4.0.1 on 2022-02-03 16:57

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_on', models.DateTimeField(auto_created=True, auto_now=True)),
                ('feedback_message', models.CharField(max_length=250)),
                ('given_by', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('about', models.CharField(choices=[('Grampanchayat', 'Grampanchayat'), ('Education', 'Education'), ('Tourism', 'Tourism')], default='Grampanchayat', max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_on', models.DateTimeField(auto_created=True, auto_now=True)),
                ('notice_message', models.CharField(max_length=200)),
                ('attachment', cloudinary.models.CloudinaryField(blank=True, max_length=255)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
