# Generated by Django 4.0.1 on 2022-01-31 17:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_notice_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='attachment',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
    ]
